user:
  # 开关
  start: true
  type: "dir"  # dir or file
  json-dir: "C:\\Users\\Administrator\\Desktop\\data\\06-14\\"
  sql-dir: "C:\\Users\\Administrator\\Desktop\\data\\06-14\\sqlfile\\"
  json-file: "jsonfile/ssss.json"
  sql-file: "sqlfile/ssss.json"
  ignore-type: # 
    - "基本信息"
