user:
  # 开关
  start: true
  type: "file"  # dir or file
  json-dir: "C:\\Users\\Public\\Nwt\\cache\\recv\\邓波\\"
  sql-dir: "C:\\Users\\Administrator\\Desktop\\data\\06-14\\sqlfile\\"
  json-file: "广州长隆集团有限公司.txt"
  sql-file: "广州长隆集团有限公司.sql"
  web: false
  ignore-type: # 
    - "基本信息"
